version: '3.9'

services:
  tc_gguf:
    image: adrianpga/ggufserve:1.0.0-Phi-3-mini-4k-instruct-fp16
    container_name: local-llm-2
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TEMPERATURE=0.9
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
